version: "3.9"

services:
  db:
    container_name: db
    image: postgres:13
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  event-log:
    container_name: event-log
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: "/bin/server"
    ports:
      - "5000:5000"
    depends_on:
      - db
